name: KabloTv kontrol
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'  
jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2
        
      - name: Python 3.11.8 Yükle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8
          
      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel requests
          
      - name: kablo.py Çalıştır
        run: python kablo.py
        
      - name: Commit and push the M3U8 files
        run: |
           git config --global user.name "actions-user"
           git config --global user.email "actions@github.com"
          
           git add kablo.m3u
           git diff --staged --quiet || git commit -m "RedKablo M3U8 files"
           git push --force
